-- ============================================
-- PAN NUMBER VALIDATION PROJECT
-- STEP 1: CREATE TABLES
-- ============================================

CREATE TABLE STG_PAN_NUMBERS_DATASET
(
    PAN_NUMBER TEXT
);

CREATE TABLE CLEAN_PAN_NUMBERS
(
    ORIGINAL_PAN TEXT,
    CLEAN_PAN TEXT
);

CREATE TABLE PAN_VALIDATION_AUDIT
(
    AUDIT_ID SERIAL PRIMARY KEY,
    ORIGINAL_INPUT TEXT,
    CLEAN_PAN TEXT,
    PAN_STATUS TEXT,
    VALIDATION_MESSAGE TEXT,
    VALIDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ACCEPTED_USER_PANS
(
    PAN_ID SERIAL PRIMARY KEY,
    ORIGINAL_INPUT TEXT,
    CLEAN_PAN TEXT UNIQUE,
    ACCEPTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);