-- ============================================
-- PAN NUMBER VALIDATION PROJECT
-- STEP 2: DATA CLEANING
-- ============================================


-- 1. CHECK TOTAL RECORDS

SELECT COUNT(*) AS TOTAL_RECORDS
FROM STG_PAN_NUMBERS_DATASET;


-- 2. CHECK NULL VALUES

SELECT *
FROM STG_PAN_NUMBERS_DATASET
WHERE PAN_NUMBER IS NULL;


-- 3. COUNT NULL VALUES

SELECT COUNT(*) AS NULL_COUNT
FROM STG_PAN_NUMBERS_DATASET
WHERE PAN_NUMBER IS NULL;


-- 4. CHECK DUPLICATE PAN NUMBERS

SELECT
    PAN_NUMBER,
    COUNT(*) AS DUPLICATE_COUNT
FROM STG_PAN_NUMBERS_DATASET
GROUP BY PAN_NUMBER
HAVING COUNT(*) > 1;


-- 5. COUNT DUPLICATE PAN TYPES

SELECT COUNT(*) AS DUPLICATE_PAN_TYPES
FROM
(
    SELECT PAN_NUMBER
    FROM STG_PAN_NUMBERS_DATASET
    GROUP BY PAN_NUMBER
    HAVING COUNT(*) > 1
) AS T;


-- 6. CHECK LEADING / TRAILING SPACES

SELECT PAN_NUMBER
FROM STG_PAN_NUMBERS_DATASET
WHERE PAN_NUMBER <> TRIM(PAN_NUMBER);


-- 7. COUNT PAN NUMBERS WITH SPACES

SELECT COUNT(*) AS PAN_WITH_SPACES
FROM STG_PAN_NUMBERS_DATASET
WHERE PAN_NUMBER <> TRIM(PAN_NUMBER);


-- 8. CHECK LOWERCASE PAN NUMBERS

SELECT PAN_NUMBER
FROM STG_PAN_NUMBERS_DATASET
WHERE PAN_NUMBER <> UPPER(PAN_NUMBER);


-- 9. CREATE CLEAN PAN DATA

INSERT INTO CLEAN_PAN_NUMBERS
(
    ORIGINAL_PAN,
    CLEAN_PAN
)
SELECT
    PAN_NUMBER AS ORIGINAL_PAN,
    UPPER(TRIM(PAN_NUMBER)) AS CLEAN_PAN
FROM STG_PAN_NUMBERS_DATASET;


-- 10. VIEW CLEAN DATA

SELECT *
FROM CLEAN_PAN_NUMBERS;